### ISSUE TITLE
Update to v1.6.x

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#143]
Various additions were made in v1.2.4, including the addition of a new System DeviceType, and a Starlight effect.

Starlight is available on the non-Chroma BlackWidow Ultimate 2016, however it is not yet present in the Chroma product line selection (in Synapse).

- [x] System effects - PR #189 
- [x] Starlight Effect - SDK issues tracked in #172 
- [x] Product GUIDs
- [x] New Grid - SDK issues tracked in #168 

*For reference, the docs for v1.2.4 are from v1.2.2.*

**Comment by Sharparam** [comment]
Protip: You can use checkboxes for progress tracking in issues:

 * [ ] Not done
 * [x] Done

**Comment by Sharparam** [comment]
If starlight is only available on non-Chroma devices, how is it applicable to Colore/Chroma?

**Comment by brandonscott** [comment]
@Sharparam Because it's noted as "To:Do" in the Docs.

**Comment by njbmartin** [comment]
Now that 1.6.1 is public (although buggy), we can now introduce the new features added in 1.6.x

**Comment by Sharparam** [comment]
The changes that need to be made on `Color` means backwards compatibility will break, moving this to 5.0 milestone.

**Comment by brandonscott** [comment]
My absence due to illness delayed the addition of the new Grid/Key Position design.  Adam and I are discussing the design implementation with a view to get this in as soon as possible.

**Comment by brandonscott** [comment]
- Decision to remove the comparison between Custom and Color[] due to the introduction of an additional array.

**Comment by Sharparam** [comment]
Pushed `feature/new-grid` with a whole host of changes to implement this new key grid. Put thoughts as comments here.

**Comment by brandonscott** [comment]
As discussed [Custom.cs#L74](https://github.com/CoraleStudios/Colore/blob/4ede0b741d8b8b8f42ad52a90142777a74369f1d/Corale.Colore/Razer/Keyboard/Effects/Custom.cs#L74) is unneeded as Keys have to be specifically set due to the flag. 

Also, does this mean that [Custom.cs#L92](https://github.com/CoraleStudios/Colore/blob/4ede0b741d8b8b8f42ad52a90142777a74369f1d/Corale.Colore/Razer/Keyboard/Effects/Custom.cs#L92) would "override"?  I'm unsure which array takes precedence.

**Comment by Sharparam** [comment]
Dealt with those issues in the latest commits.

If I'm getting the SDK documentation right, then entries in the key array will take precedence if the upper byte is set to `0x01` (or maybe any value that sets the first bit of that byte).

**Comment by brandonscott** [comment]
Odd behaviour occurring on Razer Blade Stealth (US).

Example:
- When setting **Left Shift** as a key, it does not set.
- When setting the **letter B** as a key, it sets **letter N**.
- Delete key sets **Backslash**.
- When setting 0x0401

**Comment by Sharparam** [comment]
And the user layout is same as the physical one?

**Comment by brandonscott** [comment]
Yes, US locale selected.

**Comment by Sharparam** [comment]
Re: (4,0) vs (4,1). Isn't this expected behaviour since the shift key on US keyboards is wide enough to span two columns and when using raw position mode we do not expect it to respect layout differences.

**Comment by brandonscott** [comment]
Hm, I was personally expecting it to be how I described. Imagine the snake app over a grid, with it advancing a key per "tick". With this implementation, one tick over (4,1) would result in nothing happening.

**Comment by brandonscott** [comment]
To document this, the issue related to the Blade having incorrect keys being set is now fixed.  The root cause of this was the new `CustomKey` effect not being present in the enum.  As a result of this, the `Custom` effect was being passed to the SDK with the `CustomKey` struct.

**Comment by brandonscott** [comment]
This issue seems to have been hijacked for everything up until SDK v1.7.2.  New grid has been implemented but @WolfspiritM has commented that the expected result does not occur on a German keyboard.  Moreover, Starlight effects also do not work.  We believe these to be SDK issues.

@Sharparam Shall we track these as separate issues, where #168 has been created and this implementation is complete?  We'd need one more for the Starlight effect.

**Comment by Sharparam** [comment]
The new system effect types haven't been added yet so this issue is still relevant and not yet finished.

Starlight not working is likely an SDK issue so should be handled in a separate issue and not be considered to be holding this one back as it's implemented correctly on our side.

**Comment by njbmartin** [comment]
Agreed with the separate tracking. Can @WolfspiritM investigate this further with the Sample SDK?

https://github.com/njbmartin/ChromaSDK-SampleApp

**Comment by brandonscott** [comment]
@njbmartin Seems like @WolfspiritM already has: 

> I assume this is an SDK issue as setting Key.Z from C++ does the same.

**Comment by njbmartin** [comment]
If that's the case, then @WolfspiritM should raise it with Mark to get that investigated by Razer.

**Comment by brandonscott** [comment]
Indeed, being tracked in #168.

**Comment by brandonscott** [comment]
System effects blocked now pending confirmation on the `Size` and `Param` fields.

**Comment by Sharparam** [comment]
All items have been implemented now. Issues that originate on the SDK side have separate tracking issues.
